/* ============================================================
   Durable Workflow Remote Staging Test

   Controlled end-to-end verification of the authenticated durable
   workflow lifecycle against the staging Supabase database.

   Fixtures (all created only when execution is explicitly enabled):
     - 1 staging-only owner Auth user
     - 1 staging-only non-member Auth user
     - 1 workspace (via server-only create_workspace RPC)
     - 1 task in that workspace
     - 1 plan version (draft v1) + 1 approval request (pending)
     - 1 plan revision v2 + 1 plan approval (approved)
     - 1 safe-internal run + 1 private artifact + 1 storage object at
         {workspace_id}/{artifact_id}/plan-brief-v2.md
     - audit events generated by the above

   Every test call goes through the server-authorized dispatcher
   in server-durable-routes.js. The script never calls Supabase
   directly except for the documented bootstrap and cleanup paths
   (workspace create, storage upload/download, exact-ID cleanup).

   The script is INCAPABLE of contacting staging unless
   MARINA_RUN_REMOTE_STAGING_TESTS=1 is explicitly set.
   Cleanup is INCAPABLE of running unless
   MARINA_CLEANUP_STAGING_TESTS=1 is also set.
   The two flags are checked independently.

   Default behavior: non-networking dry-run that prints the planned
   phases, the exact approval sentence required, and exits 0
   without touching any remote state.
   ============================================================ */
const path = require("node:path");
const { Readable } = require("node:stream");
try { require("dotenv").config({ path: ".env.local" }); } catch {}
const assert = require("node:assert/strict");

const PROJECT_REF = "sslgswhhlujryjlrnnfr";
const RUN_GUARD = process.env.MARINA_RUN_REMOTE_STAGING_TESTS;
const CLEANUP_GUARD = process.env.MARINA_CLEANUP_STAGING_TESTS;
const SUPABASE_URL = process.env.SUPABASE_URL || "";
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || "";
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

const APPROVAL_SENTENCE = [
  "I approve creating two labelled staging-only Auth test users,",
  "one owner workspace, one task, its test plan version(s) and approval,",
  "one safe-internal run with its persisted events/audit records,",
  "and one private artifact plus its exact storage object in project",
  PROJECT_REF + " for durable-workflow verification. The test may verify",
  "owner, non-member, and anonymous authorization boundaries and will",
  "delete only its exact recorded test fixtures and storage object when",
  "MARINA_CLEANUP_STAGING_TESTS=1 is set.",
].join(" ");

function log(p, m) { console.log("[" + p + "] " + m); }
function banner(t) { console.log(""); console.log("=".repeat(56)); console.log("  " + t); console.log("=".repeat(56)); }
function printDryRun() {
  banner("Durable Workflow Remote Tests — DRY RUN (no-op)");
  console.log("");
  console.log("Guards:");
  console.log("  MARINA_RUN_REMOTE_STAGING_TESTS = " + JSON.stringify(RUN_GUARD) + ' (must be "1")');
  console.log("  MARINA_CLEANUP_STAGING_TESTS  = " + JSON.stringify(CLEANUP_GUARD) + ' (must be "1")');
  console.log("  Target project ref             = " + PROJECT_REF);
  console.log("  SUPABASE_URL present           = " + Boolean(SUPABASE_URL));
  console.log("  Service role key present      = " + Boolean(SUPABASE_SERVICE_ROLE_KEY));
  console.log("");
  console.log("Planned phases (all skipped in dry-run):");
  console.log("  1.  Verify project-ref guard against SUPABASE_URL");
  console.log("  2.  Load @supabase/supabase-js and server-durable-routes");
  console.log("  3.  Create labelled owner + non-member Auth test users");
  console.log("  4.  Create owner workspace via server-only create_workspace RPC");
  console.log("  5.  Create task in that workspace via POST /api/durable/tasks");
  console.log("  6.  Generate draft plan v1 + bound approval via /api/durable/plans/generate");
  console.log("  7.  Create plan revision v2 via /api/durable/plans/revise");
  console.log("  8.  Stale-hash approve test asserts 409 stale_approval");
  console.log("  9.  Real-hash approve v2 via /api/durable/plans/decide");
  console.log("  10. Start safe-internal run via POST /api/durable/runs/start");
  console.log("  11. Read run events via /api/durable/runs/:id/events");
  console.log("  12. Fetch private artifact download URL via /api/durable/artifacts/download-url");
  console.log("  13. Read audit events via /api/durable/audit");
  console.log("  14. Test authorization boundaries (non-member + anonymous)");
  console.log("  15. If MARINA_CLEANUP_STAGING_TESTS=1, delete ONLY the recorded fixtures");
  console.log("");
  console.log("Required approval sentence before any remote test runs:");
  console.log("  " + APPROVAL_SENTENCE);
  console.log("");
  console.log("Status: DRY RUN COMPLETE — no staging resources touched.");
  process.exit(0);
}

if (RUN_GUARD !== "1") {
  printDryRun();
}

if (!SUPABASE_URL.includes(PROJECT_REF)) {
  console.error("");
  console.error("FATAL: SUPABASE_URL does not contain expected project ref.");
  console.error("  Expected substring: " + PROJECT_REF);
  console.error("  Got:                 " + (SUPABASE_URL ? SUPABASE_URL.replace(/\/\/.*@/, "//***@") : "(empty)"));
  console.error("Refusing to contact staging. Aborting before any remote request.");
  process.exit(2);
}
if (!SUPABASE_SERVICE_ROLE_KEY) {
  console.error("");
  console.error("FATAL: SUPABASE_SERVICE_ROLE_KEY is required to bootstrap the test fixtures.");
  process.exit(2);
}
if (!SUPABASE_ANON_KEY) {
  console.error("");
  console.error("FATAL: SUPABASE_ANON_KEY is required to sign in the test users.");
  process.exit(2);
}

let createClient;
try {
  ({ createClient } = require("@supabase/supabase-js"));
} catch {
  console.error("");
  console.error("FATAL: @supabase/supabase-js is not installed. Run: npm install");
  process.exit(2);
}

let durableRoutes;
try {
  durableRoutes = require(path.join(__dirname, "..", "server-durable-routes"));
} catch (err) {
  console.error("");
  console.error("FATAL: server-durable-routes could not be loaded:", err.message);
  process.exit(2);
}

const serviceClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const timestamp = Date.now();
const RUN_SUFFIX = "durable-" + timestamp;

const manifest = {
  runSuffix: RUN_SUFFIX,
  ownerEmail: "marina-staging-owner-" + RUN_SUFFIX + "@test.invalid",
  nonMemberEmail: "marina-staging-nonmember-" + RUN_SUFFIX + "@test.invalid",
  password: "Staging-Durable-" + timestamp + "!",
  ownerUserId: null,
  ownerAccessToken: null,
  nonMemberUserId: null,
  nonMemberAccessToken: null,
  workspaceId: null,
  taskId: null,
  draftPlanId: null,
  draftPlanApprovalId: null,
  approvedPlanId: null,
  approvedPlanPayloadHash: null,
  revisionPlanId: null,
  runId: null,
  artifactId: null,
  artifactStoragePath: null,
  cleanupPerformed: false,
  retainedForReview: false,
};

function makeReqRes({ method, url, headers = {}, body }) {
  let emittedEnd = false;
  const data = body == null ? "" : (typeof body === "string" ? body : JSON.stringify(body));
  const stream = new Readable({
    read() {
      if (!emittedEnd) {
        emittedEnd = true;
        this.push(data);
        this.push(null);
      }
    },
  });
  stream.method = method;
  stream.url = url;
  stream.headers = { "content-type": "application/json", ...headers };
  let statusCode = null;
  let bodyOut = null;
  let headersOut = {};
  const res = {
    headersSent: false,
    writeHead(code, hdrs) {
      statusCode = code;
      if (hdrs) headersOut = Object.assign({}, headersOut, hdrs || {});
      return this;
    },
    end(payload) {
      this.headersSent = true;
      bodyOut = payload == null ? "" : String(payload);
      return this;
    },
  };
  return {
    req: stream,
    res,
    capture() {
      const parsed = bodyOut ? (function () { try { return JSON.parse(bodyOut); } catch (_) { return bodyOut; } })() : null;
      return { status: statusCode, headers: headersOut, body: parsed };
    },
  };
}

async function callDurable(method, urlPath, opts) {
  opts = opts || {};
  const { body, token, query } = opts;
  let u = urlPath;
  if (query && Object.keys(query).length) {
    const sp = new URLSearchParams();
    for (const k of Object.keys(query)) {
      const v = query[k];
      if (v !== undefined && v !== null) sp.set(k, String(v));
    }
    const qs = sp.toString();
    if (qs) u += "?" + qs;
  }
  const headers = {};
  if (token) headers.authorization = "Bearer " + token;
  const handle = makeReqRes({ method, url: u, headers, body });
  await durableRoutes.handleDurable(handle.req, handle.res, new URL(u, "http://localhost"));
  return handle.capture();
}

function assertOk(result, expectedStatus, ctx) {
  if (result.status !== expectedStatus) {
    throw new Error("[" + ctx + "] expected status " + expectedStatus + ", got " + result.status + ": " + JSON.stringify(result.body));
  }
  if (result.body && result.body.ok === false) {
    throw new Error("[" + ctx + "] response.ok=false: " + result.body.message);
  }
}

function assertStatus(result, expected, ctx) {
  if (result.status !== expected) {
    throw new Error("[" + ctx + "] expected status " + expected + ", got " + result.status + ": " + JSON.stringify(result.body));
  }
}

function printManifest(prefix) {
  console.log(prefix + " Test manifest (only these IDs are touched):");
  console.log("  owner userId      = " + manifest.ownerUserId + "  email=" + manifest.ownerEmail);
  console.log("  non-member userId = " + manifest.nonMemberUserId + "  email=" + manifest.nonMemberEmail);
  console.log("  workspaceId       = " + manifest.workspaceId);
  console.log("  taskId            = " + manifest.taskId);
  console.log("  draftPlanId v1    = " + manifest.draftPlanId);
  console.log("  draftPlanApprovalId v1 = " + manifest.draftPlanApprovalId);
  console.log("  revisionPlanId v2 = " + manifest.revisionPlanId);
  console.log("  approvedPlanId    = " + manifest.approvedPlanId);
  console.log("  runId             = " + manifest.runId);
  console.log("  artifactId        = " + manifest.artifactId);
  console.log("  artifactStoragePath = " + manifest.artifactStoragePath);
  console.log("  runSuffix         = " + manifest.runSuffix);
  console.log("  cleanupPerformed  = " + manifest.cleanupPerformed);
  console.log("  retainedForReview = " + manifest.retainedForReview);
}


async function phase1_projectGuard() {
  log("Phase 1", "Project-ref guard verified: SUPABASE_URL contains " + JSON.stringify(PROJECT_REF) + ".");
}

async function phase2_createUsers() {
  log("Phase 2", "Creating labelled owner + non-member Auth test users...");
  const ownerRes = await serviceClient.auth.admin.createUser({
    email: manifest.ownerEmail, password: manifest.password, email_confirm: true,
  });
  if (ownerRes.error) throw new Error("Owner create failed: " + ownerRes.error.message);
  manifest.ownerUserId = ownerRes.data.user.id;
  log("Phase 2", "Owner created: " + manifest.ownerEmail + " (" + manifest.ownerUserId + ")");

  const nmRes = await serviceClient.auth.admin.createUser({
    email: manifest.nonMemberEmail, password: manifest.password, email_confirm: true,
  });
  if (nmRes.error) throw new Error("Non-member create failed: " + nmRes.error.message);
  manifest.nonMemberUserId = nmRes.data.user.id;
  log("Phase 2", "Non-member created: " + manifest.nonMemberEmail + " (" + manifest.nonMemberUserId + ")");

  const anon = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { persistSession: false } });
  const ownerSession = await anon.auth.signInWithPassword({
    email: manifest.ownerEmail, password: manifest.password,
  });
  if (ownerSession.error) throw new Error("Owner sign-in failed: " + ownerSession.error.message);
  manifest.ownerAccessToken = ownerSession.data.session.access_token;
  const nmSession = await anon.auth.signInWithPassword({
    email: manifest.nonMemberEmail, password: manifest.password,
  });
  if (nmSession.error) throw new Error("Non-member sign-in failed: " + nmSession.error.message);
  manifest.nonMemberAccessToken = nmSession.data.session.access_token;
}

async function phase3_createWorkspace() {
  log("Phase 3", "Creating owner workspace via server-only create_workspace RPC...");
  const res = await serviceClient.rpc("create_workspace", {
    p_name: "Marina Durable Test " + RUN_SUFFIX,
    p_slug: "marina-durable-" + timestamp,
    p_owner_id: manifest.ownerUserId,
  });
  if (res.error) throw new Error("Workspace create failed: " + res.error.message);
  manifest.workspaceId = res.data;
  log("Phase 3", "Workspace created: " + manifest.workspaceId);
  const { data: mem, error: memErr } = await serviceClient
    .from("workspace_memberships").select("role")
    .eq("user_id", manifest.ownerUserId).eq("workspace_id", manifest.workspaceId).single();
  if (memErr) throw new Error("Membership check failed: " + memErr.message);
  assert.equal(mem.role, "owner", "owner role required");
}

async function phase4_createTask() {
  log("Phase 4", "Creating task via POST /api/durable/tasks (owner)...");
  const res = await callDurable("POST", "/api/durable/tasks", {
    body: {
      workspaceId: manifest.workspaceId,
      title: "Staging durable test " + RUN_SUFFIX,
      desiredOutcome: "Verify the durable task plan run artifact lifecycle on staging.",
      instructions: "MarinaAI durable-workflow remote test fixture. Safe to delete.",
      priority: "Low",
    },
    token: manifest.ownerAccessToken,
  });
  assertOk(res, 200, "createTask");
  manifest.taskId = res.body.task.id;
  assert.equal(res.body.task.workspaceId, manifest.workspaceId);
  assert.equal(res.body.task.status, "draft");
  log("Phase 4", "Task created: " + manifest.taskId);

  const get1 = await callDurable("GET", "/api/durable/tasks/" + manifest.taskId, {
    token: manifest.ownerAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertOk(get1, 200, "getTask");
  assert.equal(get1.body.task.id, manifest.taskId);

  const list1 = await callDurable("GET", "/api/durable/tasks", {
    token: manifest.ownerAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertOk(list1, 200, "listTasks");
  assert.ok(list1.body.tasks.some((t) => t.id === manifest.taskId));
}

async function phase5_generatePlan() {
  log("Phase 5", "Generating draft plan v1 via POST /api/durable/plans/generate...");
  const res = await callDurable("POST", "/api/durable/plans/generate", {
    body: { workspaceId: manifest.workspaceId, taskId: manifest.taskId },
    token: manifest.ownerAccessToken,
  });
  assertOk(res, 200, "generatePlan");
  manifest.draftPlanId = res.body.plan.id;
  manifest.draftPlanApprovalId = res.body.planApproval.id;
  assert.equal(res.body.planner.id, "deterministic-local-planner");
  assert.equal(res.body.plan.status, "draft");
  assert.equal(res.body.plan.version, 1);
  assert.ok(Array.isArray(res.body.plan.steps) && res.body.plan.steps.length > 0);
  manifest.approvedPlanPayloadHash = res.body.payloadHash;
  log("Phase 5", "Draft plan v1: " + manifest.draftPlanId);
  log("Phase 5", "Pending approval: " + manifest.draftPlanApprovalId);
  log("Phase 5", "Payload hash: " + manifest.approvedPlanPayloadHash);
}

async function phase6_revision() {
  log("Phase 6", "Creating plan revision v2 via POST /api/durable/plans/revise...");
  const rev = await callDurable("POST", "/api/durable/plans/revise", {
    body: { workspaceId: manifest.workspaceId, planId: manifest.draftPlanId, feedback: "Refine step ordering" },
    token: manifest.ownerAccessToken,
  });
  assertOk(rev, 200, "revisePlan");
  manifest.revisionPlanId = rev.body.plan.id;
  assert.equal(rev.body.plan.version, 2);
  assert.notEqual(rev.body.plan.id, manifest.draftPlanId);
  const v1 = await callDurable("GET", "/api/durable/plans/" + manifest.draftPlanId, {
    token: manifest.ownerAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertOk(v1, 200, "getPlanV1");
  assert.equal(v1.body.plan.version, 1);
  const list = await callDurable("GET", "/api/durable/plans", {
    token: manifest.ownerAccessToken,
    query: { workspaceId: manifest.workspaceId, taskId: manifest.taskId },
  });
  assertOk(list, 200, "listPlans");
  const versions = list.body.plans.map((p) => p.version).sort();
  assert.deepEqual(versions, [1, 2]);
  log("Phase 6", "Revision v2: " + manifest.revisionPlanId);
}


async function phase7_staleHash() {
  log("Phase 7", "Stale-hash approve test asserts policy_blocked...");
  // The hash captured at v1 generation is stale after a v2 revise.
  const res = await callDurable("POST", "/api/durable/plans/decide", {
    body: {
      workspaceId: manifest.workspaceId,
      planId: manifest.revisionPlanId,
      decision: "approve",
      payloadHash: manifest.approvedPlanPayloadHash,
    },
    token: manifest.ownerAccessToken,
  });
  assertStatus(res, 409, "staleHashApprove");
  assert.equal(res.body && res.body.code, "stale_approval");
  log("Phase 7", "Stale-hash approval correctly rejected (policy binding works).");
}

async function phase8_approveV2() {
  log("Phase 8", "Reading v2 approval record to get the real payload hash, then approving v2...");
  const approvals = await callDurable("GET", "/api/durable/approvals", {
    token: manifest.ownerAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertOk(approvals, 200, "listApprovals");
  const v2Approval = approvals.body.approvals.find(
    (a) => a.actionTarget === manifest.revisionPlanId && a.actionType === "plan.approve"
  );
  assert.ok(v2Approval, "v2 plan approval record must exist");
  const realHash = v2Approval.payloadHash;
  const res = await callDurable("POST", "/api/durable/plans/decide", {
    body: {
      workspaceId: manifest.workspaceId,
      planId: manifest.revisionPlanId,
      decision: "approve",
      payloadHash: realHash,
    },
    token: manifest.ownerAccessToken,
  });
  assertOk(res, 200, "approveV2");
  assert.equal(res.body.plan.status, "approved");
  manifest.approvedPlanId = manifest.revisionPlanId;
  manifest.approvedPlanPayloadHash = realHash;
  log("Phase 8", "Plan v2 approved (id=" + manifest.approvedPlanId + ").");
}

async function phase9_startRun() {
  log("Phase 9", "Starting safe-internal run via POST /api/durable/runs/start...");
  const res = await callDurable("POST", "/api/durable/runs/start", {
    body: {
      workspaceId: manifest.workspaceId,
      taskId: manifest.taskId,
      planId: manifest.approvedPlanId,
    },
    token: manifest.ownerAccessToken,
  });
  assertOk(res, 200, "startRun");
  manifest.runId = res.body.run.id;
  manifest.artifactId = res.body.artifact.id;
  assert.equal(res.body.run.status, "succeeded");
  assert.equal(res.body.artifact.state, "ready");
  manifest.artifactStoragePath = manifest.workspaceId + "/" + manifest.artifactId + "/plan-brief-v2.md";
  log("Phase 9", "Run succeeded: " + manifest.runId);
  log("Phase 9", "Artifact ready: " + manifest.artifactId);
  log("Phase 9", "Expected storage path: " + manifest.artifactStoragePath);
}

async function phase10_runEvents() {
  log("Phase 10", "Reading persisted run events via /api/durable/runs/:id/events...");
  const res = await callDurable("GET", "/api/durable/runs/" + manifest.runId + "/events", {
    token: manifest.ownerAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertOk(res, 200, "runEvents");
  const events = res.body.events || [];
  for (let i = 1; i < events.length; i++) {
    assert.ok(events[i].sequence > events[i - 1].sequence,
      "run event sequence must increase: " + events[i - 1].sequence + " -> " + events[i].sequence);
  }
  const names = events.map((e) => e.event);
  assert.ok(names.includes("run.queued"), "run.queued event required");
  assert.ok(names.includes("run.started"), "run.started event required");
  assert.ok(names.includes("artifact.ready"), "artifact.ready event required");
  assert.ok(names.includes("run.succeeded"), "run.succeeded event required");
  log("Phase 10", "Persisted events: " + events.length + " (" + names.join(", ") + ")");
}

async function phase11_artifactDownload() {
  log("Phase 11", "Fetching private artifact download URL via /api/durable/artifacts/download-url...");
  const res = await callDurable("POST", "/api/durable/artifacts/download-url", {
    body: {
      workspaceId: manifest.workspaceId,
      artifactId: manifest.artifactId,
      filename: "plan-brief-v2.md",
    },
    token: manifest.ownerAccessToken,
  });
  assertOk(res, 200, "artifactDownloadUrl");
  assert.ok(res.body.url && res.body.url.startsWith("http"), "download URL must be http(s)...");
  log("Phase 11", "Signed download URL issued (length=" + res.body.url.length + ").");
  const head = await serviceClient.storage.from("artifacts").download(manifest.artifactStoragePath);
  if (head.error) {
    throw new Error("Storage object missing at " + manifest.artifactStoragePath + ": " + head.error.message);
  }
  assert.ok(head.data, "storage download returned data");
  const text = await head.data.text();
  assert.ok(text.length > 0, "artifact content is non-empty");
  log("Phase 11", "Storage object verified at " + manifest.artifactStoragePath + " (" + text.length + " bytes).");
}

async function phase12_audit() {
  log("Phase 12", "Reading audit events via /api/durable/audit...");
  const res = await callDurable("GET", "/api/durable/audit", {
    token: manifest.ownerAccessToken,
    query: { workspaceId: manifest.workspaceId, limit: "200" },
  });
  assertOk(res, 200, "audit");
  const events = res.body.events || [];
  const actions = new Set(events.map((e) => e.action));
  for (const required of ["plan.generated", "plan.revised", "plan.approved", "workflow.succeeded"]) {
    assert.ok(actions.has(required), "audit must contain " + required + " (saw " + Array.from(actions).join(", ") + ")");
  }
  log("Phase 12", "Audit events: " + events.length + " (actions: " + Array.from(actions).join(", ") + ").");
}

async function phase13_authBoundaries() {
  log("Phase 13", "Verifying non-member and anonymous denial...");
  const nmList = await callDurable("GET", "/api/durable/tasks", {
    token: manifest.nonMemberAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertStatus(nmList, 403, "nonMemberListTasks");
  const nmGetTask = await callDurable("GET", "/api/durable/tasks/" + manifest.taskId, {
    token: manifest.nonMemberAccessToken, query: { workspaceId: manifest.workspaceId },
  });
  assertStatus(nmGetTask, 403, "nonMemberGetTask");
  const nmStart = await callDurable("POST", "/api/durable/runs/start", {
    body: { workspaceId: manifest.workspaceId, taskId: manifest.taskId, planId: manifest.approvedPlanId },
    token: manifest.nonMemberAccessToken,
  });
  assertStatus(nmStart, 403, "nonMemberStartRun");
  const anonList = await callDurable("GET", "/api/durable/tasks", {
    query: { workspaceId: manifest.workspaceId },
  });
  assertStatus(anonList, 401, "anonymousListTasks");
  const anonUrl = await callDurable("POST", "/api/durable/artifacts/download-url", {
    body: { workspaceId: manifest.workspaceId, artifactId: manifest.artifactId, filename: "plan-brief-v2.md" },
  });
  assertStatus(anonUrl, 401, "anonymousArtifactDownload");
  log("Phase 13", "Non-member + anonymous denial confirmed.");
}


async function phase15_cleanup() {
  if (CLEANUP_GUARD !== "1") {
    console.log("");
    console.log("[Phase 15] MARINA_CLEANUP_STAGING_TESTS is not \"1\" — retaining ALL fixtures for manual review.");
    manifest.retainedForReview = true;
    printManifest("  Retained:");
    return;
  }
  console.log("");
  console.log("[Phase 15] MARINA_CLEANUP_STAGING_TESTS=1 — deleting ONLY the recorded test fixtures...");
  const errors = [];
  if (manifest.artifactStoragePath) {
    const r = await serviceClient.storage.from("artifacts").remove([manifest.artifactStoragePath]);
    if (r.error) errors.push("storage.remove " + manifest.artifactStoragePath + ": " + r.error.message);
    else log("Phase 15", "Storage object removed: " + manifest.artifactStoragePath);
  }
  if (manifest.artifactId) {
    const r = await serviceClient.from("artifacts").delete().eq("id", manifest.artifactId);
    if (r.error) errors.push("artifacts.delete " + manifest.artifactId + ": " + r.error.message);
    else log("Phase 15", "Artifact record removed: " + manifest.artifactId);
  }
  if (manifest.runId) {
    const r = await serviceClient.from("run_events").delete().eq("run_id", manifest.runId);
    if (r.error) errors.push("run_events.delete by run_id: " + r.error.message);
    const r2 = await serviceClient.from("runs").delete().eq("id", manifest.runId);
    if (r2.error) errors.push("runs.delete " + manifest.runId + ": " + r2.error.message);
    else log("Phase 15", "Run + run events removed: " + manifest.runId);
  }
  if (manifest.draftPlanApprovalId) {
    const r = await serviceClient.from("approval_requests").delete().eq("id", manifest.draftPlanApprovalId);
    if (r.error) errors.push("approval_requests.delete " + manifest.draftPlanApprovalId + ": " + r.error.message);
  }
  if (manifest.revisionPlanId) {
    const ap = await serviceClient.from("approval_requests").delete().eq("action_target", manifest.revisionPlanId);
    if (ap.error) errors.push("approval_requests by action_target: " + ap.error.message);
    const ps = await serviceClient.from("plan_steps").delete().eq("plan_id", manifest.revisionPlanId);
    if (ps.error) errors.push("plan_steps by plan_id: " + ps.error.message);
    const r = await serviceClient.from("plans").delete().eq("id", manifest.revisionPlanId);
    if (r.error) errors.push("plans.delete " + manifest.revisionPlanId + ": " + r.error.message);
    else log("Phase 15", "Plan v2 removed: " + manifest.revisionPlanId);
  }
  if (manifest.draftPlanId) {
    const ps = await serviceClient.from("plan_steps").delete().eq("plan_id", manifest.draftPlanId);
    if (ps.error) errors.push("plan_steps by plan_id (v1): " + ps.error.message);
    const r = await serviceClient.from("plans").delete().eq("id", manifest.draftPlanId);
    if (r.error) errors.push("plans.delete v1: " + r.error.message);
    else log("Phase 15", "Plan v1 removed: " + manifest.draftPlanId);
  }
  if (manifest.taskId) {
    const r = await serviceClient.from("tasks").delete().eq("id", manifest.taskId);
    if (r.error) errors.push("tasks.delete " + manifest.taskId + ": " + r.error.message);
    else log("Phase 15", "Task removed: " + manifest.taskId);
  }
  if (manifest.workspaceId) {
    const r = await serviceClient.from("workspaces").delete().eq("id", manifest.workspaceId);
    if (r.error) errors.push("workspaces.delete " + manifest.workspaceId + ": " + r.error.message);
    else log("Phase 15", "Workspace removed: " + manifest.workspaceId);
  }
  if (manifest.ownerUserId) {
    const r = await serviceClient.auth.admin.deleteUser(manifest.ownerUserId);
    if (r.error) errors.push("auth.deleteUser owner: " + r.error.message);
    else log("Phase 15", "Owner user removed: " + manifest.ownerUserId);
  }
  if (manifest.nonMemberUserId) {
    const r = await serviceClient.auth.admin.deleteUser(manifest.nonMemberUserId);
    if (r.error) errors.push("auth.deleteUser non-member: " + r.error.message);
    else log("Phase 15", "Non-member user removed: " + manifest.nonMemberUserId);
  }
  if (errors.length) {
    console.error("");
    console.error("Cleanup encountered errors:");
    for (const e of errors) console.error("  " + e);
    printManifest("  Retained after partial cleanup:");
    manifest.retainedForReview = true;
    throw new Error("cleanup did not complete; see retained manifest above");
  }
  manifest.cleanupPerformed = true;
  console.log("");
  console.log("Cleanup complete: all recorded fixtures removed (exact-ID deletes only).");
}

async function main() {
  await phase1_projectGuard();
  await phase2_createUsers();
  await phase3_createWorkspace();
  await phase4_createTask();
  await phase5_generatePlan();
  await phase6_revision();
  await phase7_staleHash();
  await phase8_approveV2();
  await phase9_startRun();
  await phase10_runEvents();
  await phase11_artifactDownload();
  await phase12_audit();
  await phase13_authBoundaries();
  await phase15_cleanup();

  console.log("");
  console.log("=".repeat(56));
  console.log("  ALL DURABLE WORKFLOW PHASES PASSED");
  console.log("=".repeat(56));
  if (manifest.cleanupPerformed) {
    console.log("  Cleanup: PERFORMED (only the exact recorded fixtures were deleted).");
  } else if (manifest.retainedForReview) {
    console.log("  Cleanup: RETAINED FOR REVIEW (set MARINA_CLEANUP_STAGING_TESTS=1 to delete).");
  }
  if (CLEANUP_GUARD !== "1") {
    console.log("");
    console.log("  Tip: re-run with MARINA_CLEANUP_STAGING_TESTS=1 to delete the retained fixtures.");
  }
}

main().catch((err) => {
  console.error("");
  console.error("=".repeat(56));
  console.error("  DURABLE WORKFLOW REMOTE TEST FAILED: " + err.message);
  console.error("=".repeat(56));
  if (manifest && (manifest.workspaceId || manifest.ownerUserId)) {
    printManifest("  Fixtures retained for review:");
  }
  if (CLEANUP_GUARD === "1") {
    console.error("");
    console.error("  MARINA_CLEANUP_STAGING_TESTS=1 was set — attempting exact-manifest cleanup before exit...");
    phase15_cleanup().then(() => {
      console.error("  Cleanup result: success.");
      process.exit(1);
    }).catch((cerr) => {
      console.error("  Cleanup result: failed:", cerr.message);
      process.exit(1);
    });
  } else {
    console.error("  No automatic cleanup will be performed (MARINA_CLEANUP_STAGING_TESTS != \"1\").");
    process.exit(1);
  }
});

